#! /bin/sh

bspc monitor DVI-I-1 -d I II III
bspc monitor HDMI-1-1 -d IV V VI

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Thunar state=floating
bspc rule -a Geary state=floating

~/.config/bspwm/start-apps.sh

