#!/bin/bash

bspc monitor HDMI-0 -d 1 2 3
bspc monitor DVI-I-1 -d 4 5 6

bspc config border_width          3
bspc config window_gap            0

bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config pointer_motion_interval     20
bspc config focused_border_color        "#C9CBFF"
bspc config normal_border_color         "#575268"

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
#bspc rule -a Thunar state=floating
bspc rule -a zoom state=floating
bspc rule -a Thunderbird desktop='^3' follow=on

killall -q polybar sxhkd dunst
wmname LG3D # Fixes problems with JDK versions assuming a reparenting window manager

# Restore wallpaper
feh --bg-fill "$HOME/.config/bspwm/wallpapers/blue_unicat.png" &

# Set display preferences
#xset s off
#xset -dpms
xset s blank
xset s 1800 # blank screen when inactive for 30 minutes

# Restore cursor theme
xsetroot -cursor_name left_ptr &

# Email client
pgrep -x thunderbird > /dev/null || thunderbird &

# Keyboard shortcuts
while pgrep -u $UID -x sxhkd > /dev/null; do sleep 0.1; done
sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &

# Notifications daemon
while pgrep -u $UID -x dunst > /dev/null; do sleep 0.1; done
dunst -conf "$HOME/.config/bspwm/dunst/dunstrc" &

# Polybar
while pgrep -u $UID -x polybar > /dev/null; do sleep 0.1; done
for m in $(polybar --list-monitors | cut -d":" -f1); do
    MONITOR=$m polybar -q main -c "$HOME/.config/bspwm/polybar/config.ini" &
done

# Compositor
pgrep -x picom > /dev/null || picom &
