#!/bin/bash

bspc monitor HDMI-0 -d 1 2 3
bspc monitor DVI-I-1 -d 4 5 6

bspc config border_width          0
bspc config window_gap            10

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false

bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Thunar state=floating
bspc rule -a Thunderbird desktop='^3' follow=on
#bspc rule -a Signal desktop='^6' follow=on

wmname LG3D # Fixes problems with JDK versions assuming a reparenting window manager

~/.config/bspwm/start-apps.sh
